### ISSUE TITLE
sharing doc links are broken

### ISSUE THREAD

**Issue by AIC-BV** [wintercms/wn-nabu-theme#3]
I noticed that sharing WinterCMS links are broken:
https://wintercms.com/docs/v1.2/docs/backend/lists#partial
=> #partial gets replaced with #using-list-filters (because of the JS scrolling event replacing the parameter?)

**Comment by bennothommo** [comment]
I've noticed this too. I think we'll just need to implement something that waits until after the doc loader is complete before moving the viewport to the anchor, since there seems to be something shifting it around during the load process.

**Comment by AIC-BV** [comment]
It is like the font and CSS are being loaded to late causing a layout shift

**Comment by LukeTowers** [comment]
Perhaps our resident speed demon @jaxwilko has some thoughts 😉

**Comment by AIC-BV** [comment]
Also these buttons are being rendered in the flow before getting absolute positioning, definitly layout shift/CSS load issues
<img width="1094" alt="image" src="https://github.com/wintercms/wn-nabu-theme/assets/89913092/56f37798-9a8e-492a-8f43-ac5e12c93d1f">

**Comment by LukeTowers** [comment]
This has been fixed.
